### ISSUE TITLE
Node should fetch transactions already added to blockchain from peer nodes on the startup.

### ISSUE THREAD

**Issue by prem-baranwal** [Talentica/simpleblockchain#27]
A node should fetch all the transactions already added to the blockchain from the peer nodes on startup.

1. If it has started afresh, it should fetch all data whereas if it has restarted after a crash, it should fetch only the missing transactions.
2. This should not be consensus responsibility.
3. Applicable for both Validator and Auditor roles

**Comment by gauravagarwaltal** [comment]
Done
