### ISSUE TITLE
Client: Not able to transfer the full balance to other users

### ISSUE THREAD

**Issue by prem-baranwal** [Talentica/simpleblockchain#42]
Steps: 
Using wallet_client_app:
1. Check the balance of user1. Say it is 100.
2. Transfer all the 100 coins to another user user2.
3. Verify the balance of user1.
Outcome: Nothing is transferred
Expected: All 100 coins should be transferred and the balance should be 0.

**Comment by gauravagarwaltal** [comment]
Fixed
